export const input_students = [
  { id: 0, name: "강상택", visible: true },
  { id: 1, name: "권정주", visible: true },
  { id: 2, name: "김민영", visible: true },
  { id: 3, name: "김성은", visible: true },
  { id: 4, name: "김영재", visible: true },
  { id: 5, name: "김윤미", visible: true },
  { id: 6, name: "김윤서", visible: true },
  { id: 7, name: "김종민", visible: true },
  { id: 8, name: "김현진", visible: true },
  { id: 9, name: "김효민", visible: true },
  { id: 10, name: "남기연", visible: true },
  { id: 11, name: "문원규", visible: true },
  { id: 12, name: "민택기", visible: true },
  { id: 13, name: "박민서", visible: true },
  { id: 14, name: "박준상", visible: true },
  { id: 15, name: "배준혁", visible: true },
  { id: 16, name: "배효정", visible: true },
  { id: 17, name: "사혜빈", visible: true },
  { id: 18, name: "신경남", visible: true },
  { id: 19, name: "신수연", visible: true },
  { id: 20, name: "양유진", visible: true },
  { id: 21, name: "양은서", visible: true },
  { id: 22, name: "양채연", visible: true },
  { id: 23, name: "양현정", visible: true },
  { id: 24, name: "오지영", visible: true },
  { id: 25, name: "이영은", visible: true },
  { id: 26, name: "이의섭", visible: true },
  { id: 27, name: "이정복", visible: true },
  { id: 28, name: "이제용", visible: true },
  { id: 29, name: "이종혁", visible: true },
  { id: 30, name: "임건애", visible: true },
  { id: 31, name: "정용준", visible: true },
  { id: 32, name: "조원희", visible: true },
  { id: 33, name: "주민경", visible: true },
  { id: 34, name: "박소희", visible: true },
];

export const defaultSeatList = [
  [0, 0],
  [0, 1],
  [0, 2],
  [0, 3],
  [0, 4],
  [0, 5],
  [0, 6],
  [0, 7],
  [1, 0],
  [1, 1],
  [1, 2],
  [1, 3],
  [1, 4],
  [1, 5],
  [1, 6],
  [1, 7],
  [2, 0],
  [2, 1],
  [2, 2],
  [2, 3],
  [2, 4],
  [2, 5],
  [2, 6],
  [2, 7],
  [3, 0],
  [3, 1],
  [3, 2],
  [3, 3],
  [3, 4],
  [3, 5],
  [3, 6],
  [3, 7],
  [4, 0],
  [4, 1],
  [4, 2],
  [4, 3],
  [4, 4],
  [4, 5],
  [4, 6],
  [4, 7],
];
