export const input_students = [
  { id: 0, name: "강상택", isFront: true },
  { id: 1, name: "권정주", isFront: true },
  { id: 2, name: "김민영", isFront: true },
  { id: 3, name: "김성은", isFront: true },
  { id: 4, name: "김영재", isFront: true },
  { id: 5, name: "김윤미", isFront: true },
  { id: 6, name: "김윤서", isFront: true },
  { id: 7, name: "김종민", isFront: true },
  { id: 8, name: "김현진", isFront: true },
  { id: 9, name: "김효민", isFront: true },
  { id: 10, name: "남기연", isFront: true },
  { id: 11, name: "문원규", isFront: true },
  { id: 12, name: "민택기", isFront: true },
  { id: 13, name: "박민서", isFront: true },
  { id: 14, name: "박준상", isFront: true },
  { id: 15, name: "배준혁", isFront: true },
  { id: 16, name: "배효정", isFront: true },
  { id: 17, name: "사혜빈", isFront: true },
  { id: 18, name: "신경남", isFront: true },
  { id: 19, name: "신수연", isFront: true },
  { id: 20, name: "양유진", isFront: true },
  { id: 21, name: "양은서", isFront: true },
  { id: 22, name: "양채연", isFront: true },
  { id: 23, name: "양현정", isFront: true },
  { id: 24, name: "오지영", isFront: true },
  { id: 25, name: "이영은", isFront: true },
  { id: 26, name: "이의섭", isFront: true },
  { id: 27, name: "이정복", isFront: true },
  { id: 28, name: "이제용", isFront: true },
  { id: 29, name: "이종혁", isFront: true },
  { id: 30, name: "임건애", isFront: true },
  { id: 31, name: "정용준", isFront: true },
  { id: 32, name: "조원희", isFront: true },
  { id: 33, name: "주민경", isFront: true },
  { id: 34, name: "박소희", isFront: true },
];

export const defaultSeatList = [
  [0, 0],
  [0, 1],
  [0, 2],
  [0, 3],
  [0, 4],
  [0, 5],
  [0, 6],
  [0, 7],
  [1, 0],
  [1, 1],
  [1, 2],
  [1, 3],
  [1, 4],
  [1, 5],
  [1, 6],
  [1, 7],
  [2, 0],
  [2, 1],
  [2, 2],
  [2, 3],
  [2, 4],
  [2, 5],
  [2, 6],
  [2, 7],
  [3, 0],
  [3, 1],
  [3, 2],
  [3, 3],
  [3, 4],
  [3, 5],
  [3, 6],
  [3, 7],
  [4, 0],
  [4, 1],
  [4, 2],
  [4, 3],
  [4, 4],
  [4, 5],
  [4, 6],
  [4, 7],
];

export const MOCK_OUTPUT = [
  { id: 0, name: "강상택", isFront: true, seat: [0, 0] },
  { id: 1, name: "권정주", isFront: true, seat: [0, 1] },
  { id: 2, name: "김민영", isFront: true, seat: [0, 2] },
  { id: 3, name: "김성은", isFront: true, seat: [0, 3] },
  { id: 4, name: "김영재", isFront: true, seat: [0, 4] },
  { id: 5, name: "김윤미", isFront: true, seat: [0, 5] },
  { id: 6, name: "김윤서", isFront: true, seat: [0, 6] },
  { id: 7, name: "김종민", isFront: true, seat: [0, 7] },
  { id: 8, name: "김현진", isFront: true, seat: [1, 0] },
  { id: 9, name: "김효민", isFront: true, seat: [1, 1] },
  { id: 10, name: "남기연", isFront: true, seat: [1, 2] },
  { id: 11, name: "문원규", isFront: true, seat: [1, 3] },
  { id: 12, name: "민택기", isFront: true, seat: [1, 4] },
  { id: 13, name: "박민서", isFront: true, seat: [1, 5] },
  { id: 14, name: "박준상", isFront: true, seat: [1, 6] },
  { id: 15, name: "배준혁", isFront: true, seat: [1, 7] },
  { id: 16, name: "배효정", isFront: true, seat: [2, 0] },
  { id: 17, name: "사혜빈", isFront: true, seat: [2, 1] },
  { id: 18, name: "신경남", isFront: true, seat: [2, 2] },
  { id: 19, name: "신수연", isFront: true, seat: [2, 3] },
  { id: 20, name: "양유진", isFront: true, seat: [2, 4] },
  { id: 21, name: "양은서", isFront: true, seat: [2, 5] },
  { id: 22, name: "양채연", isFront: true, seat: [2, 6] },
  { id: 23, name: "양현정", isFront: true, seat: [2, 7] },
  { id: 24, name: "오지영", isFront: true, seat: [3, 0] },
  { id: 25, name: "이영은", isFront: true, seat: [3, 1] },
  { id: 26, name: "이의섭", isFront: true, seat: [3, 2] },
  { id: 27, name: "이정복", isFront: true, seat: [3, 3] },
  { id: 28, name: "이제용", isFront: true, seat: [3, 4] },
  { id: 29, name: "이종혁", isFront: true, seat: [3, 5] },
  { id: 30, name: "임건애", isFront: true, seat: [3, 6] },
  { id: 31, name: "정용준", isFront: true, seat: [3, 7] },
  { id: 32, name: "조원희", isFront: true, seat: [4, 0] },
  { id: 33, name: "주민경", isFront: true, seat: [4, 3] },
  { id: 34, name: "박소희", isFront: true, seat: [4, 4] },
];
